name: talkative
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  provider: any
  shared_preferences: any
  flutter_animate: any
  intl: any
  google_fonts: any
  get_it: any
  image_picker: any
  cached_network_image: any
  supabase_flutter: ^2.15.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: any
  emoji_picker_flutter: any
  record: any
  audioplayers: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/talkative.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/talkative.jpeg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/talkative.jpeg"
    background_color: "#1E1E1E"
